### ISSUE TITLE
[Question] CSS modules

### ISSUE THREAD

**Issue by lonix1** [jouni-kantola/templated-assets-webpack-plugin#137]
Can this plugin be used somehow to enable css modules with ASP.NET Core?

I know it can be done when using a SPA (angular, react), but I'm using server-rendered pages via RazorPages.

In that case, can I use this plugin somehow to enable css modules per *server-rendered page*?

**Comment by jouni-kantola** [comment]
Let me ask a question back first: If you code split by route, would you you really need to render separate razor views per page?

**Comment by lonix1** [comment]
To be honest I'm new to webpack so unsure what that even means. :smile:

What I'm doing is I have one output, and all my stuff goes into `bundle.js` and `bundle.css`, and is referenced in `_Layout.scss`. The libraries (jquery/bootstrap/etc) are separate and referenced in same way.

In blazor/angular/etc you can localise css - I'm looking for a way to do that per razor (cshtml) page. So each page would import its own js/css.

I thought maybe this library could help with that?

**Comment by jouni-kantola** [comment]
First, as you're working with razor, I recommend you to use this plugin to have less configuration to worry about:
https://www.npmjs.com/package/razor-partial-views-webpack-plugin

Back to your question:
Yes, you can achieve what you want. And you have multiple options to do so. But before digging to deep into how to generate specific Razor views I recommend you to leave as much work as possible to webpack. Check this:
https://webpack.js.org/guides/code-splitting/

I'll give you an example that hopefully provides a bit of guidance.

For code that is for a specific page, add the following in your JavaScript:
```javascript
if(window.location.pathname === "/my-page") {
  import(/* webpackChunkName: "my-page" */ "./my-page").then((module) => {});
}
```

Start there and see how far you get.

**Comment by lonix1** [comment]
razor-partial-views-webpack-plugin : nice... didn't realize that's you too!

If I understand you correctly:
- for `n` cshtml pages, I should have `n` entrypoints
- each generates a pair of files: `contactus.bundle.js` and `contactus.bundle.css`
- they are referenced via `<script>` and `<link>` in the `ContactUs.cshtml` page
- common assets used on all pages could be generated via a "common" entrypoint
- I'd continue to reference libraries (jquery/etc.) separately or via CDN

I thought there was some voodoo to get this working, but this seems pretty simple!

Is this how you do it?

**Comment by jouni-kantola** [comment]
In essence, yes. That example you gave would work. It however doesn't utilize dynamic imports. With dynamic imports you only need one entry point. Start with multiple entry points until you feel comfortable with webpack. Good job!

**Comment by lonix1** [comment]
No good job to you, for making these nice libraries! I see you are getting 100s of downloads on npm, now that is something to be proud of! :+1:

Dynamic imports is a little too complex for my needs. But I'll look into it too, thanks.

But back to the original question! :) I obviously completely misunderstood this library. If it doesn't do what I was expecting, what does it really do?

**Comment by jouni-kantola** [comment]
I wouldn't say you misunderstood. Just that webpack itself can do more work before creating extra assets. Both `templated-assets-webpack-plugin` and `razor-partial-views-webpack-plugin` are built for generating these extra assets, which reference or inline assets generated by webpack. Most common use case is for creating scripts tags, but any asset can be referenced/inlined. An example use case for inlining is to create one asset that contains CSS that's needed at page load ("critical CSS").

**Comment by lonix1** [comment]
I see. Thanks for your advice!

**Comment by jouni-kantola** [comment]
If use use "[contenthash]" for naming files with webpack based on content (in particular for production builds), these plugins are useful for you. 

Good luck 👍
