### ISSUE TITLE
Filename for style templates contains full asset filename

### ISSUE THREAD

**Issue by ckhampus** [jouni-kantola/templated-assets-webpack-plugin#58]
When generating templates for stylesheets to resulting filename contains the full filename (including hashes) of the asset.

The filename looks like this `styles.d7e5ff8704be0c4b2bcdb26024d206ad.css.html` instead of omething like this `styles.html`.

This can be reproduced with the example in this repo. Just set `filename: "styles.[contenthash].css"` in the `ExtractTextPlugin`.

**Comment by jouni-kantola** [comment]
This is an oversight on my end that hashed files will be added to `compilation.assets`. Of course there will be. The tricky part is that they don't include a name.

This is my initial suggestion, please give input what you think:
Add property `name` to a rule's `output` object, for specifying the templated asset's name (if needed). This would probably require allowing either a `string` or `function`. The former to override the default templated asset's name, and the function for rules matching multiple assets.
Example:
```javascript
rules: [
  {
    name: "app",
    output: {
      // resulting templated asset's filename: an-example.html
      name: "an-example"
    }
  },
  {
    test: /\.css$/,
    output: {
      // resulting templated asset's filename
      // for extracted styles.[contenthash].css: styles.html
      name: (defaultName) => return defaultName.split(".")[0] 
    }
  }
];
```

What do you think?

**Comment by niklasHagner** [comment]
That `name` property would work as a temporary work-around.
But seems a bit too complicated for a permanent solution.
(I would not expect to have to add a string split function to the configuration just to get the unhashed name)

**Comment by jouni-kantola** [comment]
@niklasHagner: First off, I want to clarify that the string split was an example. If you're only using a single `styles.123245.css` you could use the `name` configured as string option (as in the first example `"an-example"`).

Regarding, `useUnhashedName`: How would one detect a hash with the `useUnhashedName`? We don't know in advance where a user has chosen to put a hash in the filename. That was the usecase the function would handle, where you could have i.e. multiple assets matched by one rule.

**Comment by jouni-kantola** [comment]
I went with the proposed suggestion and added a `output.name`. Updated example to showcase exactly the usecase with `filename: "styles.[contenthash].css"` when using `ExtractTextPlugin`.

**Comment by jouni-kantola** [comment]
`v1.2.0` now published to npm with the functionality to configure templated asset's name.

**Comment by niklasHagner** [comment]
> We don't know in advance where a user has chosen to put a hash in the filename.

I see now. Disregard my comment 😸 
Nice update 👍
